import { expect, test, type Page } from '@playwright/test';
import {
  nextStepTotpCode,
  staleTotpCode,
  totpCodeAt,
  totpStepAt,
  waitForStepAfter,
} from './support/authenticator';
import {
  createOrganizationThroughApi,
  JOURNEY_PASSWORD,
  registerAndVerify,
  signIn,
  uniqueEmail,
  uniqueSlug,
} from './support/journey';
import { linkFromEmail, waitForEmail } from './support/mailpit';

/**
 * PHASE 2'S EXIT CRITERION, AS ONE TEST.
 *
 * `roadmap.md`'s Phase 2 exit reads "the full authentication journey passes
 * E2E", and the plan's Task 18 spells out every step of it. This file is that
 * sentence made executable. It has been the phase's one unmet criterion since
 * Task 6, and a manual pass by the operator on 2026-09-07 deliberately did not
 * satisfy it — the criterion says *automated*.
 *
 * # It is serial, and that is not laziness
 *
 * `fullyParallel` is on for the rest of the suite. A journey is a single
 * ordered story about one account: the account must exist before it can enrol,
 * enrol before it can be challenged, and be a member before it can switch. Each
 * step's precondition is the previous step's postcondition, so there is nothing
 * to parallelise and a shared-state failure would be the test's fault rather
 * than the product's.
 *
 * # What it does NOT stub
 *
 * The verification and invitation links are read out of **Mailpit's HTTP API**,
 * not generated by the test. That is the plan's wording and it is the coverage
 * that matters: the defect this phase actually shipped was `TOKEN_LINK_PATHS`
 * naming `/accept-invitation` while no screen served it, and no test could see
 * it because no test followed a link out of an inbox (ruling 143). The TOTP
 * codes are generated by an implementation that shares no code with the API's,
 * for the reason `support/authenticator.ts` documents.
 *
 * # The one step that is not the UI
 *
 * Creating an organisation goes through the API, because no screen for it
 * exists — see `support/journey.ts`. It is marked in the step title so a reader
 * of the report cannot mistake it for a covered path.
 */

test.describe.serial('the full authentication journey', () => {
  const owner = uniqueEmail('owner');
  const invitee = uniqueEmail('invitee');
  const firstOrgName = 'Journey First';
  const secondOrgName = 'Journey Second';
  const firstOrgSlug = uniqueSlug('first');
  const secondOrgSlug = uniqueSlug('second');

  let ownerPage: Page;
  let mfaSecret = '';
  let firstOrgId = '';
  let secondOrgId = '';
  // The last TOTP step the API has accepted. The replay defence refuses
  // anything at or below it, so the next sign-in has to wait past it.
  let lastAcceptedStep = 0;

  test.beforeAll(async ({ browser }) => {
    ownerPage = await browser.newPage();
  });

  test.afterAll(async () => {
    await ownerPage.close();
  });

  test('registers and confirms an address from a link in a real email', async () => {
    await registerAndVerify(ownerPage, owner, async () => {
      const body = await waitForEmail(owner, 'Confirm your email address');
      return linkFromEmail(body, '/verify-email');
    });
  });

  test('signs in with the password alone, before any second factor exists', async () => {
    await signIn(ownerPage, owner, JOURNEY_PASSWORD);
    await expect(ownerPage).toHaveURL(/\/dashboard$/u);
  });

  test('creates two organisations — THROUGH THE API, because no screen exists', async () => {
    firstOrgId = await createOrganizationThroughApi(ownerPage, firstOrgName, firstOrgSlug);
    secondOrgId = await createOrganizationThroughApi(ownerPage, secondOrgName, secondOrgSlug);

    await ownerPage.goto('/dashboard');
    // The switcher is the proof the memberships are real and visible to the
    // product, which is what the API call has to buy for the rest of the run.
    await expect(ownerPage.getByLabel('Organisation')).toContainText(firstOrgName);
    await expect(ownerPage.getByLabel('Organisation')).toContainText(secondOrgName);
  });

  test('enrols an authenticator and is shown recovery codes once', async () => {
    await ownerPage.goto('/settings/security');

    const setup = ownerPage.getByRole('form', { name: 'Set up an authenticator' });
    await setup.getByLabel('Current password').fill(JOURNEY_PASSWORD);
    await setup.getByRole('button', { name: 'Begin enrolment' }).click();

    // Read the shared secret off the screen exactly as a user typing it into
    // their phone would. This is the handoff between the product and the
    // independent authenticator implementation.
    mfaSecret = (await ownerPage.getByTestId('mfa-secret').innerText()).trim();
    expect(mfaSecret.length).toBeGreaterThan(0);

    const confirm = ownerPage.getByRole('form', { name: 'Confirm enrolment' });
    await confirm.getByLabel('Code from your authenticator').fill(totpCodeAt(mfaSecret));
    await confirm.getByRole('button', { name: 'Confirm' }).click();

    // The recovery-code list is rendered ONLY after the API confirms enrolment,
    // so it is the one thing on this screen that cannot be visible unless the
    // second factor is really enabled. A looser assertion here — matching the
    // word "recovery" anywhere — passed against an enrolment that had not
    // completed, and the journey then sailed past a sign-in that should have
    // been challenged. That false green is why this is a testid.
    await expect(ownerPage.getByTestId('recovery-codes')).toBeVisible();
  });

  test('signs out, and the password alone is no longer enough', async () => {
    await ownerPage.getByRole('button', { name: 'Sign out' }).first().click();
    await expect(ownerPage).toHaveURL(/\/login/u);

    await signIn(ownerPage, owner, JOURNEY_PASSWORD);
    // The URL, not the heading. "Two-factor authentication" is also the text of
    // the MFA panel on `/settings/security`, so asserting on it proves the user
    // is looking at *a* page that mentions MFA rather than that the password
    // alone was refused. Being at `/login/mfa` is the claim this step makes.
    await expect(ownerPage).toHaveURL(/\/login\/mfa$/u);
  });

  test('refuses a code from outside the drift window, then accepts a fresh one', async () => {
    // A stale code rather than six random digits: random would be wrong with
    // probability 1 − 10⁻⁶, which is a flake per million runs for no benefit.
    await ownerPage.getByLabel('Authentication code').fill(staleTotpCode(mfaSecret));
    await ownerPage.getByRole('button', { name: 'Verify code' }).click();
    await expect(ownerPage.getByRole('alert').first()).toBeVisible();

    // A code the API has already accepted is refused on replay — enrolment
    // consumed the current step's code moments ago — so this uses the next
    // step's, which the ±1 drift window accepts and the replay defence has
    // never seen. Sleeping 31 seconds would also work and would put this test
    // over the default timeout.
    const code = nextStepTotpCode(mfaSecret);
    lastAcceptedStep = totpStepAt() + 1;
    await ownerPage.getByLabel('Authentication code').fill(code);
    await ownerPage.getByRole('button', { name: 'Verify code' }).click();

    await expect(ownerPage).toHaveURL(/\/dashboard$/u);
  });

  test('switches organisation, and the shell repaints without a reload', async () => {
    const switcher = ownerPage.getByLabel('Organisation');
    const placeholder = switcher.getByRole('option', { name: 'Choose an organisation' });

    // A freshly signed-in session is acting in no organisation, and the
    // placeholder option exists only while `session.activeOrganization` is
    // null. That makes its presence and absence purely session-derived — the
    // one thing on this shell that a user's own click on the `<select>` cannot
    // fake.
    await expect(placeholder).toHaveCount(1);

    await switcher.selectOption({ label: secondOrgName });

    // The assertion Task 17's review needed and no unit test could make.
    // `queryClient.clear()` empties the cache and notifies no mounted observer,
    // so the shell kept rendering the previous organisation until a reload —
    // and a green suite could not see it. Asserting WITHOUT reloading is the
    // whole point: a `page.reload()` here would hide exactly that defect.
    //
    // The placeholder disappearing proves a re-render from a *new session
    // document*. `toHaveValue` alone would not: selecting an option sets the
    // DOM value by itself, so it stays set even if React never re-renders.
    await expect(placeholder).toHaveCount(0);
    await expect(switcher).toHaveValue(secondOrgId);

    await switcher.selectOption({ label: firstOrgName });
    await expect(switcher).toHaveValue(firstOrgId);

    // A client-side navigation, not a reload: the shell remounts from the
    // query cache. If the switch had only changed the DOM and not the cached
    // session, the switcher would come back showing the stale organisation.
    // Scoped to the product navigation: the dashboard body also links to
    // Members, and an unscoped locator matches both.
    await ownerPage
      .getByRole('navigation', { name: 'Product' })
      .getByRole('link', { name: 'Members' })
      .click();
    await expect(ownerPage).toHaveURL(/\/settings\/members$/u);
    await expect(ownerPage.getByLabel('Organisation')).toHaveValue(firstOrgId);
  });

  test('invites a second person to the first organisation', async () => {
    await ownerPage.goto('/settings/members');

    const invite = ownerPage.getByRole('form', { name: 'Invite a member' });
    await invite.getByLabel('Email address').fill(invitee);
    await invite.getByLabel('Role').selectOption('ADMIN');
    await invite.getByRole('button', { name: 'Send invitation' }).click();

    await expect(ownerPage.getByText('The invitation has been sent.')).toBeVisible();
  });

  test('the invitee registers, follows the emailed link, and accepts', async ({ browser }) => {
    const inviteePage = await browser.newPage();

    try {
      await registerAndVerify(inviteePage, invitee, async () => {
        const body = await waitForEmail(invitee, 'Confirm your email address');
        return linkFromEmail(body, '/verify-email');
      });

      await signIn(inviteePage, invitee, JOURNEY_PASSWORD);
      await expect(inviteePage).toHaveURL(/\/dashboard$/u);

      // The step that could not be written before this task: the link in the
      // invitation email 404'd, because `/accept-invitation` was on no task's
      // checklist. Following it out of the inbox is the only way that class of
      // defect is visible.
      const body = await waitForEmail(invitee, `invited to ${firstOrgName}`);
      await inviteePage.goto(linkFromEmail(body, '/accept-invitation'));

      await expect(inviteePage.getByText(/joined|invitation accepted/iu).first()).toBeVisible();

      // Accepting does not switch the active organisation — the API says so
      // explicitly — so membership is proven by the switcher offering it.
      await inviteePage.goto('/dashboard');
      await expect(inviteePage.getByLabel('Organisation')).toContainText(firstOrgName);
    } finally {
      await inviteePage.close();
    }
  });

  test('revoking a session kills it on its very next request', async ({ browser }) => {
    // This step waits out a TOTP window before it can sign a second device in.
    test.setTimeout(90_000);

    // A second context signed in as the same person, so there is a session to
    // revoke that is not the one doing the revoking. Two contexts rather than
    // two pages: they must not share a cookie jar.
    const secondDevice = await browser.newContext();
    const secondPage = await secondDevice.newPage();

    try {
      // Up to ~30 seconds of real waiting, and it is unavoidable: the previous
      // step accepted a code and the replay defence refuses that step and every
      // earlier one. See `waitForStepAfter`.
      await waitForStepAfter(lastAcceptedStep);

      await signIn(secondPage, owner, JOURNEY_PASSWORD);
      await expect(secondPage).toHaveURL(/\/login\/mfa$/u);
      await secondPage.getByLabel('Authentication code').fill(totpCodeAt(mfaSecret));
      await secondPage.getByRole('button', { name: 'Verify code' }).click();
      await expect(secondPage).toHaveURL(/\/dashboard$/u);

      await ownerPage.goto('/settings/security');
      await ownerPage.getByRole('button', { name: 'Sign out all other devices' }).click();
      await ownerPage.getByRole('button', { name: 'Yes, sign the others out' }).click();

      // The criterion is "dead on its next request", so the assertion is a
      // navigation rather than a poll on a list: the revoked session must be
      // refused the moment it is used, not merely absent from a page the
      // revoker is looking at.
      await secondPage.goto('/dashboard');
      await expect(secondPage).toHaveURL(/\/login/u);
    } finally {
      await secondDevice.close();
    }
  });
});
